# MoveIt uses this configuration for controller management

trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01
  trajectory_duration_monitoring: true
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_hand_controller
    - right_hand_controller
    - left_arm_controller
    - right_arm_controller
    - both_arm_controller

  left_hand_controller:
    type: GripperCommand
    joints:
      - L_panda_finger_joint1
    action_ns: gripper_cmd
    default: true
  right_hand_controller:
    type: GripperCommand
    joints:
      - R_panda_finger_joint1
    action_ns: gripper_cmd
    default: true
  left_arm_controller:
    type: FollowJointTrajectory
    joints:
      - L_panda_joint1
      - L_panda_joint2
      - L_panda_joint3
      - L_panda_joint4
      - L_panda_joint5
      - L_panda_joint6
      - L_panda_joint7
    action_ns: follow_joint_trajectory
    default: true
  right_arm_controller:
    type: FollowJointTrajectory
    joints:
      - R_panda_joint1
      - R_panda_joint2
      - R_panda_joint3
      - R_panda_joint4
      - R_panda_joint5
      - R_panda_joint6
      - R_panda_joint7
    action_ns: follow_joint_trajectory
    default: true
  both_arm_controller:
    type: FollowJointTrajectory
    joints:
      - L_panda_joint1
      - L_panda_joint2
      - L_panda_joint3
      - L_panda_joint4
      - L_panda_joint5
      - L_panda_joint6
      - L_panda_joint7
      - R_panda_joint1
      - R_panda_joint2
      - R_panda_joint3
      - R_panda_joint4
      - R_panda_joint5
      - R_panda_joint6
      - R_panda_joint7
    action_ns: follow_joint_trajectory
    default: trues