# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_hand_controller:
      type: position_controllers/GripperActionController


    right_hand_controller:
      type: position_controllers/GripperActionController


    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_hand_controller:
  ros__parameters:
    joint: L_panda_finger_joint1
right_hand_controller:
  ros__parameters:
    joint: R_panda_finger_joint1
left_arm_controller:
  ros__parameters:
    joints:
      - L_panda_joint1
      - L_panda_joint2
      - L_panda_joint3
      - L_panda_joint4
      - L_panda_joint5
      - L_panda_joint6
      - L_panda_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
right_arm_controller:
  ros__parameters:
    joints:
      - R_panda_joint1
      - R_panda_joint2
      - R_panda_joint3
      - R_panda_joint4
      - R_panda_joint5
      - R_panda_joint6
      - R_panda_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity